### ISSUE TITLE
Issue with using 'enter' attribute

### ISSUE THREAD

**Issue by ianwalter** [fisshy/angular-drag-drop#13]
It seems if I specify a 'enter' attribute on the droppable element, it get executed right away instead of when the dragged element is hovering over the container.

**Comment by fisshy** [comment]
Will look into it!

Any specific browser?

**Comment by ianwalter** [comment]
I only tried this out on Chrome.

**Comment by boxxxie** [comment]
i'm getting different behaviour.
when i give an enter function it never gets called.
