### ISSUE TITLE
Change design when mouse is over the drop element

### ISSUE THREAD

**Issue by athieriot** [fisshy/angular-drag-drop#17]
Hi !

   It would be nice if we could customize the design of the drop element when the mouse pass over it.
   Browsers doesn't seems to consider the "hover" state when doing a drag and drop.

   If it's possible, having an additional class when hovering the drop element would be great.

Thanks

Aurélien

**Comment by fisshy** [comment]
Hey!

I will look into it!

**Comment by athieriot** [comment]
Cool !

I wanted to make a Pull Request but I didn't figure an easy way to do it. 
I tried to add a class inside the "drag-over" event but for some reasons it wasn't enough.
Beside, there was no obvious event were to remove this class.

If you don't have time and wants some help, I can try again if you already has an idea of how to do it.

Thanks anyway :)

Aurélien

**Comment by fisshy** [comment]
I added a css hover - Is that the expected behavior?

.drag:hover {
    background-color: #000;
    color:#fff;
}

**Comment by athieriot** [comment]
Did you change something in the code?

When I tried that on my side it wasn't working :(

**Comment by fisshy** [comment]
https://github.com/fisshy/angular-drag-drop/commit/90e894cb44918f92748dec07c681c78722735c55

Should solve it!

when an element is being dragged over another element then you will get a css .drag.hover

Checkout the readme!

**Comment by fisshy** [comment]
Or checkout the example CSS
https://github.com/fisshy/angular-drag-drop/blob/master/css/draganddrop.css

bower update angular-dragndrop

might have to clear the cache.

bower cache clean && bower update angular-dragndrop

**Comment by athieriot** [comment]
Sorry. I've tried but it doesn't make any difference.

Maybe I do something bad though.

I will continue to try it on different elements.

Thank you!

**Comment by mfotzler** [comment]
@fisshy that commit adds hover for the drag directive; I think @athieriot wants it on the drop directive.  I needed similar functionality so just applying the same idea of what you did with the drag directive to the drop directive worked well.

[p.s. thanks!  was awesome to see the feature I needed had been added 2 hours before I needed it :)]

**Comment by athieriot** [comment]
Oh man. Didn't noticed that. Well done !

Thanks

**Comment by fisshy** [comment]
great! So I can close the issue? :)
