### ISSUE TITLE
Drag and drop don't work in Firefox

### ISSUE THREAD

**Issue by athieriot** [fisshy/angular-drag-drop#19]
Hi,

   I am trying my project on Firefox right now and the drag'n'drop feature is completely broken.

   I will try a little bit more and try to find something more useful (Like a fix for example) but I wanted to report it.

   What seems to happen is that the drag and drop feature is not activated at all.
   Therefore it's like no event is fired. 
   No CSS class is changing and no function is called at the end.

It's weird because other HTML5 drag and drop are working fine. And as a matter of fact, I can't see any culprit difference between your code and simpler examples that could make it fail.

Thank you.

**Comment by fisshy** [comment]
Hi!

Thanks for the feedback, I haven't tested it much in Firefox, last time i tested it it worked so I just assumed it would still work, I obviously broke it somewhere. I think it has to do with the setData or some property that has to be set for Firefox.

I'm pretty sure it breaks on this https://github.com/fisshy/angular-drag-drop/blob/master/src/angular-dnd.js#L39 or on https://github.com/fisshy/angular-drag-drop/blob/master/src/angular-dnd.js#L41 row, there was a slight difference between Chrome and Firefox

I will look into it if no one does it before me :)

Thanks!

**Comment by athieriot** [comment]
Ok my bad.
The line you were afraid of are quite fine in the end.

It's just that I was faced to this bug:

http://stackoverflow.com/questions/23184362/firefox-dragstart-event-doesn-t-fire-in-hyperlink-s-children

Apparently if you have a drag element that is a children of a link (Like, say, an image), the dragstart event in Firefox won't be fired.

I guess I can close the issue :)

Thanks
