### ISSUE TITLE
end function doesn't get data

### ISSUE THREAD

**Issue by boxxxie** [fisshy/angular-drag-drop#20]
line 61

``` javascript
if(angular.isFunction(me.end)){
            $scope.$apply(function() {
              me.end(dndApi.getData(), $elem);
            });
          }
```

the function `dndApi.getData()` returns `undefined` for me

the same code for the start callback works fine, line 45.

**Comment by boxxxie** [comment]
oh, i see that `dndApi.getData()` only works if i didn't drop on a drop target.
is this intended or not?
also, this should probably be in the documentation.

**Comment by fisshy** [comment]
Drag element kan only be dropped on drop elements.

Maybe I should make it more clear.
