### ISSUE TITLE
.drop.dropable.hover class not applied

### ISSUE THREAD

**Issue by boxxxie** [fisshy/angular-drag-drop#21]
i'm using the below style sheet to try to figure out how classes are applied while dragging and dropping.

i notice that `.drop.dropable.hover` never gets applied, or at least i never see anything red on the screen. i've added more styles to this to try to make it stand out.

the other styles are applied and i can easily see when classes get applied.

``` html
<style>
  /* Drag element */
  .drag {
  background-color:white;
  }

  /* When drag element hovers another drag element */
  .drag.hover {
  background-color:blue;
  }

  /* When .drag is being dragged */
  .drag.dragging {
  background-color:purple;
  }

  /* Drop area */
  .drop {
  background-color:silver;
  }

  /* When .drag is being dragged appended to .drop */
  .drop.dropable {
  background-color:lightblue;
  }

  /* When drag element hovers a drop element */
  .drop.dropable.hover {
  background-color:red;
  border-style: solid;
  border-width: medium;
  border-color:red;
  }
</style>
```

**Comment by fisshy** [comment]
Let me look into the Bower, It might not have been published.

**Comment by boxxxie** [comment]
i see that your last commit fixed this...
i'm getting version 1.1.3 from bower, though.

**Comment by fisshy** [comment]
I just pushed bower.json update. Bower should get the 1.1.5 version now.

**Comment by boxxxie** [comment]
thanks :dancer:
