### ISSUE TITLE
both directives in element

### ISSUE THREAD

**Issue by dvidsilva** [fisshy/angular-drag-drop#6]
I have a list on which I show several elements and I can drag them to reorder them, and if I drop one in another one is supposed to nest or do whatever.

Angular says 

```
Error: [$compile:multidir] Multiple directives [drag, drop] asking for new/isolated scope on
```

I'm looking into it, hopefully to come up with a solution, but it looks like something that's useful, being able to have both directives in an element.

**Comment by floribon** [comment]
Couldn't you just use two different nested elements?

```
<div drag>
  <div drop> ... </div>
</div>
```

**Comment by dvidsilva** [comment]
I ended up doing that, had an area where the element is dragged from, and another one where it can be dropped

**Comment by fisshy** [comment]
Going to rewrite the logic this weekend, going to remove the isolated scope, Could messup badly =)

**Comment by fisshy** [comment]
Should have sold all the issues now and preventing future issues with scopes etc.

See new Readme/Exampel page for setup.

**Comment by dvidsilva** [comment]
thanks!
